#!/usr/bin/env python3
"""
CloudDrive Standalone Content Analyzer Worker
Can be run directly via:
    source /workspaces/upd/.venv/bin/activate
    python CloudDrive/workers/content_analyzer.py [--all] [--limit 100]
"""

import sys
import os
import sqlite3
import re
import argparse

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'database.sqlite')

ADULT_KEYWORDS = [
    'porn', 'xxx', 'nsfw', 'adult', 'nude', 'naked', 'erotic', 'sex', 'sexy',
    'onlyfans', 'leaked', 'boobs', 'pussy', 'dick', 'hentai', 'penis', 'vagina',
    'hardcore', 'playboy', 'xvideos', 'pornhub', 'brazzers', 'bangbros', 'strip',
    'milf', 'fetish', 'bdsm', 'erotica', 'sensual_nude', 'camgirl', 'redtube'
]

AI_MARKERS = [
    'steps:', 'sampler:', 'cfg scale:', 'seed:', 'negative prompt:',
    'model hash:', 'stable diffusion', 'midjourney', 'dall-e', 'dall·e',
    'novelai', 'fooocus', 'comfyui', 'civitai', 'adobe firefly', 'flux.1',
    'chatgpt image', 'as an ai language model', 'generated by chatgpt'
]

SUSPICIOUS_EXTENSIONS = ['.exe', '.bat', '.cmd', '.sh', '.vbs', '.phtml', '.scr', '.msi', '.php']

def analyze_filename_and_meta(name, mime_type):
    name_lower = name.lower()
    details = []

    # Adult check
    for kw in ADULT_KEYWORDS:
        if kw in name_lower:
            return 'adult_18', 90, f"Filename matched adult keyword: '{kw}'"

    # AI check
    if re.search(r'(chatgpt|dall[·-]e|midjourney|stablediffusion|sd_\d+|comfyui|flux_|novelai)', name_lower):
        return 'ai_generated', 85, "Filename matched AI generator pattern."

    # Suspicious extension
    for ext in SUSPICIOUS_EXTENSIONS:
        if name_lower.endswith(ext) or f"{ext}." in name_lower:
            return 'suspicious', 95, f"Dangerous or executable extension: '{ext}'"

    return 'safe', 70, "Standard file analysis completed; no policy violations detected."

def main():
    parser = argparse.ArgumentParser(description="CloudDrive Content Analyzer Worker")
    parser.add_argument("--all", action="store_true", help="Scan all files instead of only unclassified ones")
    parser.add_argument("--limit", type=int, default=50, help="Max files to scan")
    args = parser.parse_args()

    if not os.path.exists(DB_PATH):
        print(f"[-] Database not found at: {DB_PATH}")
        sys.exit(1)

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    query = "SELECT id, name, mime_type, content_tag FROM files "
    if not args.all:
        query += "WHERE content_tag IS NULL OR content_tag = 'unclassified' "
    query += f"ORDER BY id DESC LIMIT {args.limit}"

    cursor.execute(query)
    rows = cursor.fetchall()
    print(f"[*] Found {len(rows)} files to analyze...")

    scanned = 0
    for r in rows:
        tag, conf, details = analyze_filename_and_meta(r['name'], r['mime_type'] or '')
        cursor.execute(
            "UPDATE files SET content_tag = ?, content_confidence = ?, content_details = ? WHERE id = ?",
            (tag, conf, details, r['id'])
        )
        scanned += 1
        print(f"  [+] File #{r['id']} ({r['name']}) -> Tag: {tag} ({conf}%) | {details}")

    conn.commit()
    conn.close()
    print(f"[✓] Analysis complete! Updated {scanned} files.")

if __name__ == '__main__':
    main()
