<?php
// ========================================================
// CloudDrive Content Analyzer & Moderation Engine
// ========================================================

require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../config/google.php';

class ContentAnalyzer {

    // Adult / NSFW Keyword Dictionary
    private static $adultKeywords = [
        'porn', 'xxx', 'nsfw', 'adult', 'nude', 'naked', 'erotic', 'sex', 'sexy',
        'onlyfans', 'leaked', 'boobs', 'pussy', 'dick', 'hentai', 'penis', 'vagina',
        'hardcore', 'playboy', 'xvideos', 'pornhub', 'brazzers', 'bangbros', 'strip',
        'milf', 'fetish', 'bdsm', 'erotica', 'sensual_nude', 'camgirl', 'redtube',
        'camsoda', 'chaturbate', 'deepthroat', 'blowjob', 'creampie', 'cumshot'
    ];

    // AI Generation Signatures
    private static $aiPromptMarkers = [
        'steps:', 'sampler:', 'cfg scale:', 'seed:', 'negative prompt:',
        'model hash:', 'stable diffusion', 'midjourney', 'dall-e', 'dall·e',
        'novelai', 'fooocus', 'comfyui', 'civitai', 'adobe firefly',
        'prompt: ', 'workflow: ', 'clip skip:', 'hires upscale', 'flux.1',
        'as an ai language model', 'generated by chatgpt', 'chatgpt image'
    ];

    // Suspicious / Malicious Signatures
    private static $suspiciousSignatures = [
        'eval(base64_decode', 'shell_exec', 'passthru(', 'system(', 'popen(',
        'powershell -enc', 'cmd.exe /c', 'cscript.exe', 'wscript.exe',
        '<?php', '<script>eval', '/bin/sh', '/bin/bash', 'chmod +x'
    ];

    /**
     * Analyze a single file by ID
     */
    public static function analyzeFile(PDO $pdo, int $fileId): array {
        // 1. Invoke Python Deep Content Analyzer (inspects real image pixels, video frames with ffmpeg, and PDF text)
        $pythonBin = '/workspaces/upd/.venv/bin/python';
        $workerScript = __DIR__ . '/../workers/content_analyzer.py';
        if (file_exists($pythonBin) && file_exists($workerScript)) {
            $cmd = escapeshellcmd($pythonBin) . ' ' . escapeshellarg($workerScript) . ' --file-id ' . (int)$fileId . ' 2>&1';
            $output = @shell_exec($cmd);
            if (!empty($output)) {
                $check = $pdo->prepare("SELECT content_tag, content_confidence, content_details FROM files WHERE id = ?");
                $check->execute([$fileId]);
                $updated = $check->fetch(PDO::FETCH_ASSOC);
                if ($updated && !empty($updated['content_tag'])) {
                    return [
                        'success' => true,
                        'file_id' => $fileId,
                        'tag' => $updated['content_tag'],
                        'content_tag' => $updated['content_tag'],
                        'confidence' => (int)$updated['content_confidence'],
                        'content_confidence' => (int)$updated['content_confidence'],
                        'details' => $updated['content_details'],
                        'content_details' => $updated['content_details'],
                    ];
                }
            }
        }

        $stmt = $pdo->prepare("SELECT f.*, g.* FROM files f JOIN google_accounts g ON f.google_account_id = g.id WHERE f.id = ?");
        $stmt->execute([$fileId]);
        $file = $stmt->fetch();

        if (!$file) {
            return ['success' => false, 'error' => 'File not found.'];
        }

        $tag = 'safe';
        $confidence = 70;
        $details = [];
        $fileName = strtolower($file['name']);
        $mime = strtolower($file['mime_type']);

        // 1. Filename Heuristic Check
        foreach (self::$adultKeywords as $kw) {
            if (strpos($fileName, $kw) !== false) {
                $tag = 'adult_18';
                $confidence = 90;
                $details[] = "Filename matched adult keyword: '$kw'";
                break;
            }
        }

        if ($tag !== 'adult_18') {
            if (preg_match('/(chatgpt|dall[·-]e|midjourney|stablediffusion|sd_\d+|comfyui|flux_|novelai)/i', $fileName)) {
                $tag = 'ai_generated';
                $confidence = 85;
                $details[] = "Filename matched AI generator pattern.";
            } elseif (preg_match('/\.(exe|bat|cmd|sh|vbs|phtml|scr|msi|php)$/i', $fileName) || preg_match('/\.(jpg|png|pdf)\.(exe|sh|bat)$/i', $fileName)) {
                $tag = 'suspicious';
                $confidence = 95;
                $details[] = "Disguised or executable extension detected.";
            }
        }

        // 2. Fetch Header / Metadata from Google Drive using Range probe (first 64KB)
        $headerBytes = self::fetchFileHeaderBytes($file, $pdo, 65536);

        if (!empty($headerBytes)) {
            $headerLower = strtolower($headerBytes);

            // Check AI Generation Metadata (PNG chunks, Exif, XMP)
            $aiMatches = [];
            foreach (self::$aiPromptMarkers as $aiSig) {
                if (strpos($headerLower, $aiSig) !== false) {
                    $aiMatches[] = $aiSig;
                }
            }

            if (count($aiMatches) >= 2 || (count($aiMatches) === 1 && in_array($aiMatches[0], ['steps:', 'stable diffusion', 'midjourney', 'dall-e', 'dall·e']))) {
                $tag = 'ai_generated';
                $confidence = 95;
                $details[] = "Found embedded AI generation metadata/prompts: " . implode(', ', array_slice($aiMatches, 0, 4));
            }

            // Check Suspicious / Malware signatures
            foreach (self::$suspiciousSignatures as $sig) {
                if (strpos($headerLower, $sig) !== false) {
                    $tag = 'suspicious';
                    $confidence = 95;
                    $details[] = "Found dangerous payload pattern: '$sig'";
                    break;
                }
            }

            // Camera Exif Check (Confirms safe real-world media)
            if ($tag === 'safe' && (strpos($headerLower, 'apple') !== false || strpos($headerLower, 'samsung') !== false || strpos($headerLower, 'canon') !== false || strpos($headerLower, 'nikon') !== false || strpos($headerLower, 'sony') !== false)) {
                $confidence = 95;
                $details[] = "Verified standard camera hardware EXIF signature.";
            }
        }

        if (empty($details)) {
            $details[] = "Standard file analysis completed; no high-risk policy flags found.";
        }

        $detailsStr = implode(' | ', $details);

        // Update database record
        $upd = $pdo->prepare("
            UPDATE files 
            SET content_tag = ?, content_confidence = ?, content_details = ? 
            WHERE id = ?
        ");
        $upd->execute([$tag, $confidence, $detailsStr, $fileId]);

        return [
            'success' => true,
            'file_id' => $fileId,
            'content_tag' => $tag,
            'content_confidence' => $confidence,
            'content_details' => $detailsStr,
        ];
    }

    /**
     * Batch analyze unclassified or all files
     */
    public static function batchAnalyze(PDO $pdo, int $limit = 50, bool $forceAll = false): array {
        $pythonBin = '/workspaces/upd/.venv/bin/python';
        $workerScript = __DIR__ . '/../workers/content_analyzer.py';
        if (file_exists($pythonBin) && file_exists($workerScript)) {
            $flag = $forceAll ? '--all' : '';
            $cmd = escapeshellcmd($pythonBin) . ' ' . escapeshellarg($workerScript) . ' ' . $flag . ' --limit ' . (int)$limit . ' 2>&1';
            $output = @shell_exec($cmd);
            if (!empty($output)) {
                $lines = explode("\n", trim($output));
                $lastLine = end($lines);
                $json = json_decode($lastLine, true);
                if ($json && isset($json['success'])) {
                    return $json;
                }
            }
        }

        $sql = "SELECT id FROM files ";
        if (!$forceAll) {
            $sql .= "WHERE content_tag = 'unclassified' OR content_tag IS NULL ";
        }
        $sql .= "ORDER BY id DESC LIMIT " . (int)$limit;

        $stmt = $pdo->query($sql);
        $ids = $stmt->fetchAll(PDO::FETCH_COLUMN);

        $results = [];
        foreach ($ids as $id) {
            $results[] = self::analyzeFile($pdo, (int)$id);
        }

        return [
            'success' => true,
            'scanned' => count($results),
            'results' => $results,
        ];
    }

    /**
     * Helper to read the first N bytes from Google Drive using HTTP Range probe
     */
    private static function fetchFileHeaderBytes(array $file, PDO $pdo, int $bytesToRead = 65536): ?string {
        $accessToken = GoogleDriveManager::getValidAccessToken($file, $pdo);
        if (!$accessToken) return null;

        $url = "https://www.googleapis.com/drive/v3/files/{$file['google_file_id']}?alt=media";
        $endByte = $bytesToRead - 1;

        $ch = curl_init($url);
        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_HTTPHEADER => [
                'Authorization: Bearer ' . $accessToken,
                "Range: bytes=0-{$endByte}",
            ],
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_TIMEOUT => 10,
        ]);

        $data = curl_exec($ch);
        $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);

        if ($code === 200 || $code === 206) {
            return $data;
        }

        return null;
    }
}
